export const wordMap = {
  "thank you": "thanks",
  "thanks": "thanks",
  "hi": "hello",
  "hello": "hello",
  "i am from":"iamfrom",
  "good":"good",
  "z":"signz",
  "j":"signj",
  "see you later": "seeyoulater",
  "see u later": "seeyoulater",
  "me":"me",
  "i":"me",
  "father":"father",
  "mother":"mother",
};
